---
- name: download fedora
  become: yes
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/4.1.1/fcrepo-webapp-4.1.1.war owner={{ install_user }} group={{ install_group }} dest={{ install_path }}/fcrepo-webapp-4.1.1.war

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  sudo: yes

- name: check fedora.war
  become: yes
  stat: path=/var/lib/tomcat6/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  sudo: yes
  command: cp {{ install_path }}/fcrepo-webapp-4.1.1.war /var/lib/tomcat6/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  sudo: yes
  template: src=tomcat.j2 dest=/etc/tomcat6/tomcat6.conf backup=yes 
# TODO: make Java options configurable at the time of the ansible run

- name: restart tomcat
  sudo: yes
  service: name=tomcat6 enabled=yes state=restarted
