---
- name: install tomcat packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
      - tomcat6
      - tomcat6-webapps
      - tomcat6-admin-webapps

- name: set tomcat to restart on reboot
  sudo: yes
  service: name=tomcat6 enabled=yes